@Host = http://localhost:5261

GET {{Host}}/api/contacts
Accept: application/json

{
  "firstName": "Musk"
  
}

@Host = http://localhost:5063

POST {{Host}}/api/contacts/1
Content-Type: application/json

{
    "firstName": "Prime",
    "lastName": "Alex",
    "phoneNumber": "+99999999999",
    "email": "prime0201@gmail.com",
}


GET {{Host}}/api/contacts



PUT {{Host}}/api/contacts/1
Content-Type: application/json

{
  "firstName": "Figma",
  "lastName": "UI",
  "phoneNumber": "+998999999990",
  "email": "Dragon@gmail.com"
}


PATCH  {{Host}}/api/contacts/1
Content-Type: application/json

{
  "phoneNumber": "+9981111111111",
}



DELETE  {{Host}}/api/contacts/5
